style: ""
template: ""
info:
  title: "CHANGELOG"
  repository_url: "https://github.com/your-org/codespace-templates"
  intro: |
    All notable changes to this project will be documented in this file.
    
    The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/),
    and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).

options:
  commits:
    filters:
      Type:
        - feat
        - fix
        - perf
        - docs
        - refactor
        - test
        - chore
  commit_groups:
    title_maps:
      feat: "Added"
      fix: "Fixed"
      perf: "Performance"
      docs: "Documentation"
      refactor: "Refactored"
      test: "Tests"
      chore: "Chores"
  header:
    pattern: "^(\\w*)(\\(([\\w\\*\\.\-]*)\\))?:\\s*(.*)$"
    pattern_maps:
      - Type
      - Scope
      - Subject
  notes:
    keywords:
      - BREAKING CHANGE
      - BREAKING CHANGES
      - BREAKING
  issues: "github"
  issue_url: "https://github.com/your-org/codespace-templates/issues/{{.Ver}}"
